language: java
sudo: false
script: mvn clean test
notifications:
  email:
    recipients:
      - finopablo@gmail.com
    on_success: [always|never|change] # default: always
    on_failure: [always|never|change] # default: always
